import { StyleSheet } from 'react-native';

export const tabStyles = StyleSheet.create({
    tabsContainer: {
        flexDirection: 'row',
        paddingTop: 24,
        paddingBottom: 16, // Increased from 4 to prevent shadow overlap/clipping
        paddingHorizontal: 28,
        gap: 8,
        backgroundColor: 'transparent',
        marginHorizontal: 0,
        marginTop: 0,
        marginBottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tab: {
        width: 115,
        paddingVertical: 6,
        paddingHorizontal: 8,
        borderRadius: 9999,
        alignItems: 'center',
        backgroundColor: 'rgba(255, 182, 193, 0.1)',
        borderWidth: 0,
        borderColor: 'transparent',
        flexDirection: 'row', // Restore Horizontal layout
        justifyContent: 'flex-start',
        gap: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    activeTab: {
        backgroundColor: '#FFB6C1',
        borderColor: '#FF69B4',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    activeTabGradient: {
        width: 120,
        borderRadius: 9999,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    activeTabTouchable: {
        width: 120,
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 9999,
        alignItems: 'center',
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'center',
    },
    activeTabCard: {
        alignSelf: 'center',
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#F3F4F6',
        overflow: 'hidden',
    },
    activeTabCardGradient: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 16,
        alignItems: 'center',
        flexDirection: 'row',
        gap: 8,
        minWidth: 120,
        justifyContent: 'center',
    },
    activeTabCardText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
    },
    tabText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#C2185B',
        textAlign: 'center',
    },
    activeTabText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 16,
    },
});
