import { NextRequest, NextResponse } from 'next/server'

// Default configuration that matches LoginConfigManager structure
function getDefaultConfig() {
  return {
    branding: {
      appName: 'Boundary',
      logoUrl: '',
      primaryColor: '#3b82f6',
      secondaryColor: '#64748b',
      accentColor: '#10b981',
      textColor: '#1f2937',
      backgroundColor: '#ffffff',
      fontFamily: 'Inter, sans-serif',
      fontSize: '16px',
      fontWeight: '400',
      logoSize: '64px',
      faviconUrl: '',
      metaDescription: '',
      metaKeywords: '',
      customCSS: '',
      customJS: '',
      showBranding: true,
      tagline: 'Secure access for your enterprise',
      description: '',
      ssoLogoUrl: '',
      ssoLogoSize: '20px',
      providerLogos: {}
    },
    layout: {
      layout: 'centered',
      maxWidth: '400px',
      padding: '2rem',
      borderRadius: '0.5rem',
      shadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
      backdropBlur: false,
      showBranding: true,
      showFooter: true,
      footerText: '© 2024 Boundary. All rights reserved.',
      paddingTop: '2rem',
      paddingRight: '2rem',
      paddingBottom: '2rem',
      paddingLeft: '2rem',
      marginTop: '0',
      marginRight: '0',
      marginBottom: '0',
      marginLeft: '0',
      borderTopLeftRadius: '0.5rem',
      borderTopRightRadius: '0.5rem',
      borderBottomRightRadius: '0.5rem',
      borderBottomLeftRadius: '0.5rem',
      horizontalPosition: 'center',
      verticalPosition: 'center',
      useCustomPosition: false,
      buttonAlignment: 'center',
      buttonGroupLayout: 'vertical',
      buttonSpacing: 'medium',
      primaryButtonPosition: 'bottom',
      secondaryButtonPosition: 'top',
      showButtonDivider: true,
      cardFloat: 'none',
      cardZIndex: '10',
      cardTransform: '',
      stickyPosition: false,
      responsivePositioning: true,
      ssoIconOnly: false,
      ssoButtonShape: 'default'
    },
    form: {
      showEmailField: true,
      showUsernameField: false,
      showPhoneField: false,
      showCompanyField: false,
      showPasswordField: true,
      showRememberMe: true,
      showRememberDevice: false,
      showForgotPassword: true,
      showSocialLogin: true,
      showSSO: true,
      showLanguageSelector: false,
      showThemeToggle: false,
      showLoading: false,
      showErrors: false,
      showSuccessMessage: false,
      showValidation: false,
      showProgress: false,
      showCookieConsent: false,
      showPrivacyPolicy: false,
      showTermsOfService: false,
      showGDPR: false,
      showCompliance: false,
      showAccountLockoutWarning: false,
      showSessionTimeout: false,
      showSecurityQuestions: false,
      showBiometric: false,
      showKeyboardNavigation: false,
      showScreenReaderSupport: false,
      showHighContrast: false,
      showFontSizeControls: false,
      showMultiTenant: false,
      showRoleSelection: false,
      showWorkspaceSelection: false,
      showMoreSocialProviders: false,
      showSocialPreFill: false,
      showAccountLinking: false,
      emailPlaceholder: 'Enter your email',
      usernamePlaceholder: 'Username',
      phonePlaceholder: 'Phone number',
      companyPlaceholder: 'Company name',
      passwordPlaceholder: 'Enter your password',
      submitButtonText: 'Submit',
      signInButtonText: 'Sign In',
      signUpButtonText: 'Create Account',
      rememberMeText: 'Remember me',
      rememberDeviceText: 'Trust this device',
      forgotPasswordText: 'Forgot password?',
      signUpLinkText: 'Create account',
      signInLinkText: 'Sign in',
      buttonStyle: 'solid',
      buttonSize: 'medium',
      buttonBorderRadius: '0.5rem',
      buttonPadding: '0.75rem 1.5rem',
      showButtonIcons: true,
      buttonAnimation: '',
      buttonFullWidth: true,
      socialLoginText: 'Or continue with',
      ssoButtonText: 'Continue with SSO',
      loadingText: 'Loading...',
      errorMessage: 'An error occurred',
      successMessage: 'Success!',
      validationMessage: 'Please check your input',
      progressText: 'Processing...',
      cookieConsentText: 'This site uses cookies',
      privacyPolicyText: 'Privacy Policy',
      termsOfServiceText: 'Terms of Service',
      gdprText: 'GDPR compliant',
      complianceText: 'Compliance',
      accountLockoutText: 'Account locked',
      sessionTimeoutText: 'Session expired',
      securityQuestionsText: 'Security questions',
      biometricText: 'Biometric authentication',
      keyboardNavigationText: 'Keyboard navigation',
      screenReaderText: 'Screen reader support',
      highContrastText: 'High contrast',
      fontSizeText: 'Font size',
      multiTenantText: 'Select tenant',
      roleSelectionText: 'Select role',
      workspaceSelectionText: 'Select workspace',
      moreSocialProvidersText: 'More providers',
      socialPreFillText: 'Continue as',
      accountLinkingText: 'Link your account',
      sessionDuration: '3600',
      maxLoginAttempts: '5',
      supportedLanguages: ['en'],
      supportedThemes: ['light', 'dark'],
      socialProviders: ['Google', 'Microsoft', 'GitHub'],
      oauthProviders: ['google', 'microsoft'],
      ssoProviders: ['saml', 'oidc'],
      fontSizes: ['small', 'medium', 'large'],
      ssoLayout: 'vertical'
    },
    background: {
      type: 'solid',
      value: '#ffffff',
      opacity: 1,
      blur: 0,
      gradientStops: [],
      gradientDirection: 'to right',
      patternType: 'dots',
      patternColor: '#f3f4f6',
      patternSize: '20px',
      videoUrl: '',
      imageUrl: ''
    },
    signup: {
      showNameField: true,
      showEmailField: true,
      showPhoneField: false,
      showCompanyField: false,
      showPasswordField: true,
      showConfirmPasswordField: true,
      showTermsCheckbox: true,
      showPrivacyCheckbox: true,
      namePlaceholder: 'Full name',
      emailPlaceholder: 'Email address',
      phonePlaceholder: 'Phone number',
      companyPlaceholder: 'Company name',
      passwordPlaceholder: 'Password',
      confirmPasswordPlaceholder: 'Confirm password',
      submitButtonText: 'Create Account',
      signInLinkText: 'Already have an account? Sign in',
      termsLinkText: 'Terms of Service',
      privacyLinkText: 'Privacy Policy',
      buttonStyle: 'solid',
      buttonSize: 'medium',
      buttonFullWidth: true,
      showSocialLogin: true,
      socialLoginText: 'Or sign up with',
      socialProviders: ['Google', 'Microsoft', 'GitHub'],
      pageTitle: 'Create Account',
      pageSubtitle: 'Join our platform today',
      pageDescription: '',
      logoUrl: '',
      logoSize: '64px',
      logoPosition: 'top',
      showWelcomeMessage: false,
      welcomeTitle: '',
      welcomeMessage: '',
      nextSteps: '',
      redirectAfterSignup: true,
      redirectUrl: '/dashboard',
      autoLogin: false,
      showSuccessAnimation: true,
      cardWidth: '400px',
      cardPadding: '2rem',
      borderRadius: '0.5rem',
      cardShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
      cardBackground: '#ffffff',
      cardBorder: '1px solid #e5e7eb',
      formLayoutStyle: 'vertical',
      fieldSpacing: 'medium',
      fieldWidth: 'full',
      labelPosition: 'top',
      showFieldIcons: true,
      showFieldDescriptions: false,
      buttonPosition: 'bottom',
      buttonAlignment: 'center',
      buttonGroupLayout: 'vertical',
      buttonSpacing: 'medium',
      showButtonDivider: true,
      cardFloat: false,
      cardZIndex: '10',
      cardTransform: '',
      backdropBlur: false,
      stickyPosition: false,
      ssoLayout: 'vertical',
      ssoIconOnly: false,
      ssoButtonShape: 'default',
      enableValidation: true,
      passwordMinLength: 8,
      passwordRequireUppercase: true,
      passwordRequireLowercase: true,
      passwordRequireNumbers: true,
      passwordRequireSpecialChars: false,
      validateEmailDomain: false,
      validatePhoneFormat: false,
      showBranding: true
    }
  }
}

export async function GET(request: NextRequest) {
  try {
    // In a real implementation, this would fetch from your database
    // For now, return the default configuration
    const config = getDefaultConfig()
    
    return NextResponse.json(config, {
      headers: {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
      }
    })
  } catch (error) {
    console.error('Failed to fetch login config:', error)
    return NextResponse.json(
      { error: 'Failed to fetch configuration' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    // In a real implementation, this would save to your database
    // For now, just return success
    console.log('Config updated:', body)
    
    return NextResponse.json({ success: true, message: 'Configuration saved' })
  } catch (error) {
    console.error('Failed to save login config:', error)
    return NextResponse.json(
      { error: 'Failed to save configuration' },
      { status: 500 }
    )
  }
}
